# Generated by Django 4.0.3 on 2022-04-14 12:38

import PROJECT.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name_plural': 'quotes'},
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), PROJECT.web.models.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), PROJECT.web.models.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[PROJECT.web.models.only_numbers_validator]),
        ),
    ]
