# Generated by Django 4.0.3 on 2022-04-11 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_created_remove_profile_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numbers  are allowed.')]),
        ),
    ]
