# Generated by Django 4.0.3 on 2022-04-12 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numbers  are allowed.')]),
        ),
    ]
