# Generated by Django 4.0.3 on 2022-04-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_projectuser_phone_projectuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
