# Generated by Django 4.0.3 on 2022-04-14 12:38

import PROJECT.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_phone_number_projectuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), PROJECT.accounts.models.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), PROJECT.accounts.models.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[PROJECT.accounts.models.only_numbers_validator]),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[PROJECT.accounts.models.only_numbers_validator]),
        ),
    ]
